package sistema.service;

import java.util.Date;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import sistema.dao.UsuarioDAO;
import sistema.models.Grupo;
import sistema.models.Tipo;
import sistema.models.Usuario;

public class TesteBanco {

	public static void main(String[] args) {

		EntityManagerFactory factory;
		EntityManager em;
		factory = Persistence.createEntityManagerFactory("Cruzeirao");
		em = factory.createEntityManager();
		//em.find(Grupo.class, 1);
		Usuario usuario = new Usuario();
		UsuarioDAO usuariodao = new UsuarioDAO();
		usuario.setNome("Leonardo Danone");
		usuario.setEmail("leo");
		usuario.setSenha("leo123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Fim do mundo virando a esquerda");
		usuario.setCpf("555.555.555-55");
		usuario.setRg("55.555.555-5");
		usuario.setTelefoneFixo("(55) 5555-5555");
		usuario.setTelefoneMovel("(55) 55555-5555");
		usuario.setTipo(Tipo.Admin);
		usuariodao.save(usuario);
		usuario.setNome("Gustavo Ajuda");
		usuario.setEmail("gu");
		usuario.setSenha("gu123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Itu");
		usuario.setCpf("111.111.111-11");
		usuario.setRg("11.111.111-1");
		usuario.setTelefoneFixo("(11) 1111-1111");
		usuario.setTelefoneMovel("(11) 11111-1111");
		usuario.setTipo(Tipo.Admin);
		usuariodao.save(usuario);
		usuario.setNome("Affunção Brian");
		usuario.setEmail("affs");
		usuario.setSenha("affs123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Logo ali");
		usuario.setCpf("222.222.222-22");
		usuario.setRg("22.222.222-2");
		usuario.setTelefoneFixo("(22) 2222-2222");
		usuario.setTelefoneMovel("(22) 22222-2222");
		usuario.setTipo(Tipo.Admin);
		usuariodao.save(usuario);
		usuario.setNome("Torcedor");
		usuario.setEmail("torcedor");
		usuario.setSenha("123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Logo ali");
		usuario.setCpf("333.333.333-33");
		usuario.setRg("33.333.333-3");
		usuario.setTelefoneFixo("(33) 3333-3333");
		usuario.setTelefoneMovel("(33) 33333-3333");
		usuario.setTipo(Tipo.Torcedor);
		usuariodao.save(usuario);
		usuario.setNome("Diretor");
		usuario.setEmail("diretor");
		usuario.setSenha("123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Logo ali");
		usuario.setCpf("444.444.444-44");
		usuario.setRg("44.444.444-4");
		usuario.setTelefoneFixo("(44) 4444-4444");
		usuario.setTelefoneMovel("(44) 44444-4444");
		usuario.setTipo(Tipo.Diretor);
		usuariodao.save(usuario);
		usuario.setNome("Jogador");
		usuario.setEmail("jogador");
		usuario.setSenha("123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Logo ali");
		usuario.setCpf("666.666.666-66");
		usuario.setRg("66.666.666-6");
		usuario.setTelefoneFixo("(66) 6666-6666");
		usuario.setTelefoneMovel("(66) 66666-6666");
		usuario.setTipo(Tipo.Jogador);
		usuariodao.save(usuario);
		usuario.setNome("Juiz");
		usuario.setEmail("juiz");
		usuario.setSenha("123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Logo ali");
		usuario.setCpf("777.777.777-77");
		usuario.setRg("77.777.777-7");
		usuario.setTelefoneFixo("(77) 7777-7777");
		usuario.setTelefoneMovel("(77) 77777-7777");
		usuario.setTipo(Tipo.Juiz);
		usuariodao.save(usuario);
		usuario.setNome("Massagista");
		usuario.setEmail("massagista");
		usuario.setSenha("123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Logo ali");
		usuario.setCpf("888.888.888-88");
		usuario.setRg("88.888.888-8");
		usuario.setTelefoneFixo("(88) 8888-8888");
		usuario.setTelefoneMovel("(88) 88888-8888");
		usuario.setTipo(Tipo.Massagista);
		usuariodao.save(usuario);
		usuario.setNome("Organizador");
		usuario.setEmail("organizador");
		usuario.setSenha("123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Logo ali");
		usuario.setCpf("999.999.999-99");
		usuario.setRg("99.999.999-9");
		usuario.setTelefoneFixo("(99) 9999-9999");
		usuario.setTelefoneMovel("(99) 99999-9999");
		usuario.setTipo(Tipo.Organizador);
		usuariodao.save(usuario);
		usuario.setNome("Tecnico");
		usuario.setEmail("tecnico");
		usuario.setSenha("123");
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Logo ali");
		usuario.setCpf("000.000.000-00");
		usuario.setRg("00.000.000-0");
		usuario.setTelefoneFixo("(00) 0000-0000");
		usuario.setTelefoneMovel("(00) 00000-0000");
		usuario.setTipo(Tipo.Tecnico);
		usuariodao.save(usuario);
		usuario.setDataNascimento(new Date());
		usuario.setEndereco("Logo ali");
		usuario.setCpf("000.000.000-11");
		usuario.setRg("00.000.000-1");
		usuario.setTelefoneFixo("(00) 0000-1111");
		usuario.setTelefoneMovel("(00) 00000-1111");
		usuariodao.closeEntityManager();
	}
}
